# Generated by Django 6.0.3 on 2026-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanyfaq',
            name='answer_text',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='germanyfaq',
            name='question_text',
            field=models.TextField(max_length=300),
        ),
    ]
